name: Format
on:
    workflow_dispatch:
    pull_request:
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
                  persist-credentials: false
            - name: Install packages
              run: npm i
            - name: Format files
              run: npm run format
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: Format code